coverage:
  status:
    project:
      default:
        target: auto      # baseline = whatever your first run is
        threshold: 1%     # allow a little drift without failing
    patch: off            # don’t bother with per-PR patch coverage
