name: Python CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python   # 👈 run all commands from /python

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"   # match your local version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with black
        run: black --check .

      - name: Run tests with pytest
        run: pytest -v --cov=leetcode --cov-report=xml

      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}